### ISSUE TITLE
Reminders phone number format

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/bot-survey-engine#3]
When the user is asked "What is your phone number? Use E.164 format, for example +123424"

Change this to:

"What is your phone number?"

Take the user's input and do these steps:
1) Remove any characters which are not digits.
2) If number doesn't start with 1, add a 1
3) add a + in front of the number
4) Save this transformed version

**Comment by Xiaofei1010** [comment]
Followed the four steps. Also used `e164.js` to check the validation of the transformed version. More information about `e164.js` can be found here: https://www.npmjs.com/package/e164

**Comment by kylepolich** [comment]
@Xiaofei1010 great work on this!
